-- 코드를 작성해주세요 --
SELECT dev.ID, dev.EMAIL, dev.FIRST_NAME, dev.LAST_NAME
FROM DEVELOPERS AS dev
WHERE 
    (dev.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0 
    OR 
    (dev.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0
ORDER BY dev.ID