-- 코드를 작성해주세요
select SUM(HG.SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
from HR_GRADE AS HG JOIN HR_EMPLOYEES AS HE ON HE.EMP_NO = HG.EMP_NO 
GROUP BY HG.EMP_NO
order by SCORE DESC
limit 1;